FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt requirements.txt
COPY vm-database.ipynb vm-database.ipynb
COPY vm-doc-retrival.ipynb vm-doc-retrival.ipynb
COPY dataset dataset  

RUN pip install -r requirements.txt

RUN pip install jupyter

EXPOSE 8888

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--allow-root", "--no-browser", "--NotebookApp.token=''"]